config/routes.rb
PopHealth::Application.routes.draw do

  apipie

  devise_for :users, :controllers => {:registrations => "registrations"}

  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  put "admin/upload_patients"
  put "admin/upload_providers"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
  delete "admin/remove_providers"
  post 'api/measures/finalize'
  post 'api/measures/update_metadata'
  get "logs/index"

  root :to => 'home#index'

  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end

    member do
      get :merge_list
      put :merge
    end
  end

  resources :teams

  namespace :api do
    get 'reports/qrda_cat3.xml', :to =>'reports#cat3', :format => :xml
    get 'reports/cat1/:id/:measure_ids', :to =>'reports#cat1', :format => :xml
    namespace :admin do
      resource :caches do
        collection do
          get :count
        end
      end
      resource :patients do
        collection do
          get :count
        end
      end
      resource :providers do
        collection do
          get :count
        end
      end
      resources :users do
        member do
          get :enable
          get :disable
          post :promote
          post :demote
          get :approve
          get :update_npi
        end
      end
    end
    resources :providers do
      resources :patients do
        collection do
          get :manage
          put :update_all
        end
      end
    end
    resources :patients do
      member do
        get :results
      end
    end

    resources :measures

    resources :queries do
       member do
        get :patients
        get :patient_results
        put :recalculate
       end
    end
  end

end

app/views/admin/patients.html.erb
<div id="pageContent" style="padding:20px;">
<h3>Patients</h3>

  <table>

    <tr><td>patients loaded: </td>
      <td>
        <span id="patient_count"><%= @patient_count %></span> patients
      </td>
      <td>
        <%= button_to "Delete Patients", "/admin/remove_patients", 'method' => 'delete', 'class' => 'btn btn-danger'%>
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>

    <tr><td>cache counts: </td>
      <td>
        query cache: <%= @query_cache_count%> <br>
        patient cache: <%= @patient_cache_count%>
      </td>
      <td>
        <%= button_to "Delete Caches", "/admin/remove_caches", 'method' => 'delete', 'class' => 'btn btn-danger'%>
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>

    <tr><td>providers loaded: </td>
      <td>
        <%= @provider_count %> providers

      </td>
      <td>
        <%= button_to "Delete Providers", "/admin/remove_providers", 'method' => 'delete', 'class' => 'btn btn-danger'%>
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>

    <tr><td colspan="2">&nbsp;</td></tr>
    <%= form_tag("/admin/upload_patients", :method => "put", :multipart=>true, :class=>"file-upload") do %>
    <tr><td>Upload patient zip file: </td>
      <td>
        <%= file_field_tag(:file)%>
      </td>
      <td><%= submit_tag("Upload", 'class' => "btn btn-success") %></td>
    </tr>
    <% end %>

    <tr><td colspan="2">&nbsp;</td></tr>
    <%= form_tag("/admin/upload_providers", :method => "put", :multipart=>true, :class=>"file-upload") do %>
    <tr><td>Upload provider opml file: </td>
      <td>
        <%= file_field_tag(:file)%>
      </td>
      <td><%= submit_tag("Upload", 'class' => "btn btn-success") %></td>
    </tr>
    <% end %>

  </table>

</div> <!-- pageContent -->
<script>
  $(document).ready(function() {
    $(".file-upload").submit(function(e) {
      if (this.file.value === "") {
        alert("Please provide a file.");
        this.file.focus();
        e.preventDefault();
      }
    });
    (function poll(){
       setTimeout(function(){
        $.getJSON( "<%= count_api_admin_patients_path %>", function(data){
          $('#patient_count').html(data.patient_count);
          //Setup the next poll recursively
          poll();
        });
      }, 5000);
    })();
  });
</script>

app/views/admin/users.html.erb
<script type="text/javascript">
  var popHealth = popHealth || {};

  popHealth.promoteUser = function() {
    var username = $(this).data("username");
    var role = $(this).data("role");
    var parentTd = $(this).parent();
    $.post('<%= admin_promote_path %>', {'username': username, 'role': role}, function(data) {
      parentTd.html(data);
      parentTd.find('.demote').click(popHealth.demoteUser);
    });
    return false;
  };

  popHealth.demoteUser = function() {
    var username = $(this).data("username");
    var role = $(this).data("role");
    var parentTd = $(this).parent();

    if (username == '<%= current_user.username %>') {
      var response = confirm('You are about to remove admin rights from the currently logged in user' 
      +', this will cause you to immediately lose access to all admin functionality including this page.  ' 
      +'You will need to use another admin account to restore admin rights.  Are you sure you want to continue?');
      if (!response) return;
    }

    $.post('<%= admin_demote_path %>', {'username': username, 'role': role}, function(data) {
      parentTd.html(data);
      parentTd.find('.promote').click(popHealth.promoteUser);
    });
    return false;
  };

  popHealth.approveUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();
    $.post('<%= admin_approve_path %>', {'username': username}, function(data) {
      parentTd.html(data);
    });
  };

  popHealth.disableUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();

    if (username == '<%= current_user.username %>') {
      var response = confirm('You are about to disable the currently logged in user' 
      +', this will cause you to immediately lose access and be logged out.  Are you sure you want to continue?');
      if (!response) return;
    }

    popHealth.disableEnableUser(1, username, parentTd)
  };
  popHealth.enableUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();
    popHealth.disableEnableUser(0, username, parentTd)
  };
  popHealth.disableEnableUser = function(disabled, username, parentTd) {
    $.post('<%= admin_disable_path %>', {'username': username, 'disabled': disabled}, function(data) {
      parentTd.html(data);
      if (disabled == 1) parentTd.find('.disable').click(popHealth.enableUser);
      else parentTd.find('.enable').click(popHealth.disableUser);
    });
  };
  popHealth.changeNpi = function() {
    var username = $(this).data("username");
    var npi = $(this).val();
    $.post('<%= admin_update_npi_path %>', {'username': username, 'npi': npi}, function(data) {
    });
    
  };

  $(document).ready(function() {
    $('.promote').click(popHealth.promoteUser);
    $('.demote').click(popHealth.demoteUser);
    $('.approve').click(popHealth.approveUser);
    $('.enable').click(popHealth.disableUser);
    $('.disable').click(popHealth.enableUser);
    $('.npi_select').change(popHealth.changeNpi);
  });
</script>

<div id="pageContent">
<h3>Users</h3>
<table id="patientTable" class="table">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Username</th>
    <th>provider</th>
    <th>Administrator</th>
    <th>Staff Role</th>
    <th>Approved</th>
    <th>Status</th>
  </tr>
  <% @users.each do |user| -%>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.username %></td>
    <td>
      <select class="npi_select" data-username="<%= user.username %>" name="user[npi]">
        <option value="-1">&nbsp;</option>
        <% Provider.all.alphabetical.each do |provider| %>
          <option value="<%= provider.npi %>" <%= (user.npi == provider.npi) ? "selected=\"selected\"" : ""%>><%= provider.full_name%></option>
        <% end%>
      </select>
    </td>
    <td>
      <% if user.admin? -%>
      Yes - <a href="#" class="demote" data-role="admin" data-username="<%= user.username %>">revoke</a>
      <% else -%>
      No - <a href="#" class="promote" data-role="admin" data-username="<%= user.username %>">grant</a>
      <% end -%>
    </td>
    <td>
      <% if user.staff_role? -%>
      Yes - <a href="#" class="demote" data-role="staff_role" data-username="<%= user.username %>">revoke</a>
      <% else -%>
      No - <a href="#" class="promote" data-role="staff_role" data-username="<%= user.username %>">grant</a>
      <% end -%>
    </td>
    <td>
      <% if user.approved? -%>
      true
      <% else -%>
      <a href="#" class="approve" data-username="<%= user.username %>">approve</a>
      <% end -%>
    </td>
    <td>
      <a href="#" class="<%= (user.disabled?) ? 'disable' : 'enable'%>" data-username="<%= user.username %>"><%= (user.disabled?) ? 'disabled' : 'enabled'%></a>
    </td>
  </tr>
  <% end -%>
</table>
</div> <!-- pageContent -->